### PR TITLE
[175] fix bug of cases

### LINKED ISSUE #175: Bug: solving for any case
```ocaml
f(X) ->
    case X of
        ok -> 0;
        _ -> 1
    end.

main() ->
    f(true).
```

The type of the function `f/1` should be `any() -> number()`, but it does not. So this code gets a type error.
```ocaml
TODO:filename:-1: Type error: type mismatch;
  found   : 'true'
  required: 'ok'
```

### PR DESCRIPTION
**Pull request by yoshihiro503**
fix #175

### CODE REVIEW

File: lib/solver.ml [hunk 1]
```diff
@@ -73,9 +73,9 @@ let solve_sub expr sol ty1 ty2 =
   let ty1' = lookup_type sol ty1 in
   let ty2' = lookup_type sol ty2 in
   let inf = inf ty1' ty2' in
-  if is_subtype ty1' ty2' then
+  if is_subtype ty1' ty2' && ty1' <> ty2' then
```
Comment (amutake) [inline lib/solver.ml]: It is my understanding that this change aim to add new type variables (i.e., type variables which are not appeared in `sol` yet) into `sol`.
Is it correct?

If so, for example, assume `ty1` has type `number()` in `sol` and `ty2` is not included in sol, `ty2` will not be added to `sol`. Is it OK?

And, I would appreciate that you add some comments about the purpose because I am worrying that we may forget meaning of `&& ty1' <> ty2'` in the future.

File: lib/solver.ml [hunk 2]
```diff
@@ -73,9 +73,9 @@ let solve_sub expr sol ty1 ty2 =
...
     Ok sol
-  else if inf = TyBottom then
+  else if inf = TyBottom && ty1' <> TyBottom then
```
Comment (amutake) [inline lib/solver.ml]: ditto. Could you add some comments why you added `&& ty1' <> TyBottom`?

File: test/blackbox-test/test-cases/case175.erl [hunk 3]
```diff
@@ -0,0 +1,11 @@
+-module(case175).
```
[the remark this answers is not in the document]
Comment (amutake) [reply test/blackbox-test/test-cases/case175.erl]: It is issue number!
I think `case175.erl` is a bit confusing name. How about `case_univ_pattern.erl` because `_` is called as [universal pattern](http://erlang.org/doc/apps/erts/absform.html#patterns)?

[the remark this answers is not in the document]
Comment (yoshihiro503) [reply test/blackbox-test/test-cases/case175.erl]: I agree.

File: lib/solver.ml (hunk 1 above)
Comment (yoshihiro503) [reply lib/solver.ml]: > It is my understanding that this change aim to add new type variables (i.e., type variables which are not appeared in `sol` yet) into `sol`.
> Is it correct?

Yes it is.

> If so, for example, assume `ty1` has type `number()` in `sol` and `ty2` is not included in sol, `ty2` will not be added to `sol`. Is it OK?

It is no problem that variables in right hand side are not restricted in the solving algorithms.

Comment (yoshihiro503) [reply lib/solver.ml]: > And, I would appreciate that you add some comments about the purpose because I am worrying that we may forget meaning of `&& ty1' <> ty2'` in the future.

Sure it is, I will fix it.

File: lib/solver.ml (hunk 2 above)
Comment (yoshihiro503) [reply lib/solver.ml]: Yes

File: lib/solver.ml (hunk 1 above)
Comment (amutake) [reply lib/solver.ml]: > It is no problem that variables in right hand side are not restricted in the solving algorithms.

I understand. Thanks!

File: test/blackbox-test/test-cases/case175.erl (hunk 3 above)
[the remark this answers is not in the document]
Comment (yoshihiro503) [reply test/blackbox-test/test-cases/case175.erl]: fixed.

File: lib/solver.ml [hunk 4]
```diff
@@ -73,8 +73,12 @@ let solve_sub expr sol ty1 ty2 =
   let ty1' = lookup_type sol ty1 in
   let ty2' = lookup_type sol ty2 in
   let inf = inf ty1' ty2' in
+  let sol' =
+    Type.variables ty1
+    |> List.fold_left ~f:(fun sol v -> map_add_if_not_exists v TyAny sol) ~init:sol
+  in
```
Comment (amutake) [inline lib/solver.ml]: I think it is clearer than before!
