### PR TITLE
[137] support second binding of variables

### LINKED ISSUE #137: Support pattern using bound variables
In Erlang, the pattern using bound variables work as like constant pattern.
For example:

```erlang
X = 1,
case 123 of
  X -> X + 1
end.
```
↓
```console
** exception error: no case clause matching 123
```

For this, we must consider the second binding of a already bound variable.

The case of shadowing variables must also be considered, but it is a different PR https://github.com/dwango/fialyzer/issues/135.

### PR DESCRIPTION
**Pull request by yoshihiro503**
fix #137

### CODE REVIEW

File: lib/context.ml [hunk 1]
```diff
@@ -13,7 +13,12 @@ type t = Type.t MapOnKey.t
 
 let empty : t = MapOnKey.empty
 let find = Map.find
-let add key data = Map.add_exn ~key ~data
+let add key data t =
+  match Map.add ~key ~data t with
```
Comment (youxkei) [inline lib/context.ml]: Reading memo:
Using Map.add instead of Map.add_exn allows us to add an already inserted data to a map.

File: test/unit-test/test_derivation.ml [hunk 2]
```diff
@@ -161,6 +161,31 @@ let%expect_test "derivation" =
...
+   * case 123 of
+   *   X when X
+   * end
+   *)
+  let ctx = Context.empty |> Context.add (Context.Key.Var "X") (Type.of_elem TyNumber) in
+  print ctx (Case
+    (Constant (Number 123),
+      [(PatVar "X", Constant (Atom "true")), Var "X"]));
+  [%expect {|
+    (Ok (
```
Comment (youxkei) [inline test/unit-test/test_derivation.ml]: Reading memo:
With this PR, the code using a already defined variable in a case pattern can be correctly derived
