### PR TITLE
Feature/issue 177/fix bug of sup

### LINKED ISSUE #177: Bug: sup of function types
`sup (TyFun a b) (TyFun s t)` should be `(TyFun (a|s) (b|t))`.

### PR DESCRIPTION
**Pull request by yoshihiro503**
fix #177

### CODE REVIEW

File: test/unit-test/test_type.ml [hunk 1]
```diff
@@ -115,4 +115,17 @@ let%expect_test "sup" =
...
+   * see: https://github.com/dwango/fialyzer/issues/177
+   *)
+  let ty1 = of_elem (TyFun ([of_elem TyNumber], of_elem TyNumber)) in
+  let ty2 = of_elem (TyFun ([of_elem TyAtom], of_elem TyAtom)) in
+  print ty1 ty2;
+  [%expect {|
+     (TyUnion ((TyFun ((TyUnion (TyAtom TyNumber))) (TyUnion (TyNumber TyAtom)))))
+  |}];
+
+  ()
```
Comment (amutake) [inline test/unit-test/test_type.ml]: :+1:
